[workspace]
members = ["crates/iem-core", "crates/iem-server", "crates/iem-ui", "crates/iem-tray", "crates/iem-rpp", "crates/iem-dsp"]
resolver = "2"

[workspace.package]
version = "2.0.0-dev.3"
edition = "2024"
authors = ["iemmixer contributors"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/zbynekdrlik/iemmixer"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.dev]
opt-level = 1

[profile.mutants]
inherits = "test"
debug = "none"
