//! IEM Mixer Tauri Application
//!
//! Desktop shell providing tray icon, window, and installer.
//! All UI is served by the embedded Axum server.

pub mod tray;

use iem_core::Config;
use iem_server::ServerConfig;
use std::sync::OnceLock;
use tauri::{AppHandle, Manager, WindowEvent};

/// Global AppHandle storage for cross-thread access
static APP_HANDLE: OnceLock<AppHandle> = OnceLock::new();

/// Run the Tauri application
pub fn run() {
    // Set panic handler
    std::panic::set_hook(Box::new(|info| {
        tracing::error!("PANIC: {}", info);
    }));

    // Initialize logging
    let log_dir = dirs::data_dir()
        .unwrap_or_else(|| std::path::PathBuf::from("."))
        .join("iemmixer")
        .join("logs");
    std::fs::create_dir_all(&log_dir).ok();

    let file_appender = tracing_appender::rolling::daily(&log_dir, "iemmixer.log");
    let (non_blocking, _guard) = tracing_appender::non_blocking(file_appender);

    let file_layer = tracing_subscriber::fmt::layer()
        .with_writer(non_blocking)
        .with_ansi(false);

    let env_filter = tracing_subscriber::EnvFilter::from_default_env()
        .add_directive("iem_tray=debug".parse().unwrap())
        .add_directive("iem_core=debug".parse().unwrap())
        .add_directive("iem_server=info".parse().unwrap())
        // Every cloudflared /ready poll (30 s) is logged for event-time
        // tunnel diagnostics (reaperiem#202).
        .add_directive("iem_server::tunnel_watch=debug".parse().unwrap());

    use tracing_subscriber::layer::SubscriberExt;
    use tracing_subscriber::util::SubscriberInitExt;
    tracing_subscriber::registry()
        .with(env_filter)
        .with(file_layer)
        .init();

    tracing::info!(log_dir = %log_dir.display(), "Logging initialized");
    tracing::info!("Starting IEM Mixer v{}", iem_core::VERSION);

    // Site configuration (TOML); runtime secrets are generated by the server.
    let config_path = dirs::config_dir()
        .unwrap_or_else(|| std::path::PathBuf::from("."))
        .join("iemmixer")
        .join("iemmixer.toml");

    let config = if config_path.exists() {
        Config::load(&config_path).unwrap_or_else(|e| {
            tracing::error!(error = %e, path = %config_path.display(), "Failed to load the site config, using defaults");
            Config::default()
        })
    } else {
        tracing::warn!(path = %config_path.display(), "No site config found, using defaults");
        Config::default()
    };

    let port = config.port;
    let share_url = config.share_url();

    // Create Tokio runtime
    let rt = tokio::runtime::Runtime::new().expect("Failed to create Tokio runtime");
    let rt_handle = rt.handle().clone();

    // Spawn web server
    let config_dir = config_path
        .parent()
        .unwrap_or(std::path::Path::new("."))
        .to_path_buf();
    let server_config = ServerConfig {
        port,
        config,
        config_dir,
    };
    let (ready_tx, ready_rx) = tokio::sync::oneshot::channel();
    rt_handle.spawn(async move {
        if let Err(e) = iem_server::start_server(server_config, Some(ready_tx)).await {
            tracing::error!("Web server error: {}", e);
        }
    });

    // Wait for server to be ready (with timeout)
    rt_handle.block_on(async {
        match tokio::time::timeout(std::time::Duration::from_secs(10), ready_rx).await {
            Ok(Ok(())) => tracing::info!("Server ready on port {}", port),
            Ok(Err(_)) => tracing::error!("Server startup channel dropped"),
            Err(_) => tracing::error!("Server startup timed out after 10s"),
        }
    });

    // Keep runtime alive in background thread
    std::thread::spawn(move || {
        rt.block_on(std::future::pending::<()>());
    });

    // Build and run Tauri app
    tauri::Builder::default()
        .plugin(tauri_plugin_single_instance::init(|app, _args, _cwd| {
            // Focus existing window when second instance tries to start
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.set_focus();
                let _ = window.show();
            }
        }))
        .plugin(tauri_plugin_shell::init())
        .on_window_event(|window, event| {
            if let WindowEvent::CloseRequested { api, .. } = event {
                // Hide instead of close
                api.prevent_close();
                let _ = window.hide();
            }
        })
        .setup(move |app| {
            let handle = app.handle().clone();

            // Store AppHandle globally
            let _ = APP_HANDLE.set(handle.clone());

            // Setup tray
            if let Err(e) = tray::setup_tray(&handle, port, share_url) {
                tracing::error!("Failed to setup tray: {}", e);
            }

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running the iemmixer tray");
}
